/**
 * Lookup helpers for the responsive-image manifest generated by
 * scripts/optimize-images.mjs. Returns srcset/width/height for images
 * that have pre-generated WebP variants, and intrinsic dimensions for
 * the external logo files.
 */
import manifest from '../generated/responsive-images.json';

/**
 * @param {string | null | undefined} src public path of the original image
 * @param {{ maxWidth?: number }} [opts] cap variant widths (e.g. card images)
 * @returns {{ src: string, srcset: string | undefined, width: number, height: number } | null}
 */
export function getResponsiveImage(src, opts = {}) {
	if (!src) return null;
	const entry = manifest.images[src];
	if (!entry) return null;

	const maxWidth = opts.maxWidth ?? Infinity;
	const variants = entry.variants.filter((v) => v.w <= maxWidth);
	const parts = variants.map((v) => `${v.src} ${v.w}w`);
	/* The original file is the largest candidate unless a cap excludes it. */
	if (entry.width <= maxWidth) parts.push(`${src} ${entry.width}w`);

	return {
		src: variants.length > 0 ? variants[variants.length - 1].src : src,
		srcset: parts.length > 1 ? parts.join(', ') : undefined,
		width: entry.width,
		height: entry.height,
	};
}

/**
 * Intrinsic dimensions for a carousel logo, if known.
 * @param {string | null | undefined} src
 * @returns {{ width: number, height: number } | null}
 */
export function getLogoDimensions(src) {
	if (!src) return null;
	const direct = manifest.logoDims[src];
	if (direct) return direct;
	const filename = src.split('/').pop()?.split('?')[0];
	return filename ? (manifest.logoDims[`/images/${filename}`] ?? null) : null;
}
